schema: 'schema/generated/schema.graphql'

generates:
  types/client-gql-generated.d.ts:
    documents:
      - 'src/**/!(*.d).{ts,tsx}'
    config:
      noExport: true
    plugins:
      - typescript
      - typescript-operations